version: 2.1
orbs:
  gcp-cli: circleci/gcp-cli@1.8.3

parameters:
  instance-name:
    type: string 
    default: ""

commands:
  initialize-gce:
    description: "Register GCP access keys to CircleCI project"
    steps:
      - gcp-cli/initialize
  start-vm:
    steps:
      - run:
          command: |
            gcloud compute instances start << pipeline.parameters.instance-name >> \
            --zone=asia-northeast1-b
  send-notification:
    description: "Send job status to Twitter direct message"
    steps:
      - run:
          name: Set external IP address to environment variable
          command: |
            ip_addr=$(
                       gcloud compute instances describe << pipeline.parameters.instance-name >> \
                       --format='get(networkInterfaces[0].accessConfigs[0].natIP)' \
                       --zone=asia-northeast1-b \
                     )
            echo "export INSTANCE_IP=${ip_addr}" >> $BASH_ENV
      - run:
          name: Install Tweepy
          command: |
            export PIP=$(which pip pip3 | head -1)
            $PIP install tweepy --upgrade
      - run:
          name: Send Job notifcation
          command: |
            export PYTHON=$(which python python3 | tail -1)
            $PYTHON tweet.py \
            ${TWITTER_CONSUMER_KEY} \
            ${TWITTER_CONSUMER_SECRET_KEY} \
            ${TWITTER_ACCESS_TOKEN} \
            ${TWITTER_ACCESS_TOKEN_SECRET} \
            ${TWITTER_RECIPIENT}

jobs:
  build:
    docker:
      - image: google/cloud-sdk:latest
    steps:
      - checkout
      - initialize-gce
      - start-vm
      - send-notification

workflows:
  version: 2.1
  start-vm:
    jobs:
      - build:
          context: GCP
